[compiler.solc]
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]
include_paths = ["src"]

remappings = [

    "ds-test/=lib/solmate/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",    
]

[detectors]
exclude = []
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
